# Site
repository: ldhbenecia/porfolio
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: DongHyeok Lim
title: Hufs Students
email: jh07050@gmail.com
website: www.github.com/ldhbenecia

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: null
github_username: ldhbenecia
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ldh_benecia_
linkedin_username: ldhbenecia
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's DongHyeok Lim and I want to be a front-end developer.
  Currently, I am studying at the Department of Computer and Electronic System Engineering at Hankuk University of Foreign Studies.

  I am most skilled in: <mark>React</mark> and <mark>None</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 프로젝트명
        link: github.com/ldhbenecia
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          소제
        description: | # this will include new lines to allow paragraphs
          설명

  - title: Career # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Career
        # link: 경력 주소
        # link_text: boringcompany.com
        # sub_title: 무슨 직무
        # caption: 기간 언제부터
        #quote: >
        #  Summary of experiences so far
        description: | # this will include new lines to allow paragraphs
            2020.03.24 ~ 2021.09.29 대한민국 육군 보병 병장 만기전역
            2023.03 ~ 한국외국어대학교 학생 IT 자치 기구 훕스토리(Hufstory) 회장

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hankuk University of Foreign Studies
        caption: 2019 - 2025
        sub_title: Department of Computer and Electronic System Engineering
        #quote: >
        #  Hankuk University of Foreing Studies, aka HUFS, is best Foreign-study education institution in South Korea.
        description: | # this will include new lines to allow paragraphs
          2019 한국외국어대학교 컴퓨터전자시스템공학부 입학

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Front_End
      - React
      - Tailwind CSS
      - Gaming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
